package pokecube.adventures.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import pokecube.core.client.models.APokemobModel;


public class ModelMegaScizor extends APokemobModel 
{
	  //fields
	    ModelRenderer hornright;
	    ModelRenderer hornmiddle;
	    ModelRenderer hornleft;
	    ModelRenderer headbottom;
	    ModelRenderer headtop;
	    ModelRenderer neck;
	    ModelRenderer bodybottom;
	    ModelRenderer shoulderleft;
	    ModelRenderer armleft;
	    ModelRenderer clawleft;
	    ModelRenderer clawright;
	    ModelRenderer armright;
	    ModelRenderer shoulderright;
	    ModelRenderer wingsright;
	    ModelRenderer thoraxbottom;
	    ModelRenderer leglefttoe;
	    ModelRenderer thoraxtop;
	    ModelRenderer legrighttop;
	    ModelRenderer legrightmiddle;
	    ModelRenderer legrightbottom;
	    ModelRenderer legrighttoe;
	    ModelRenderer legleftbottom;
	    ModelRenderer legleftmiddle;
	    ModelRenderer leglefttop;
	    ModelRenderer bodytop;
	    ModelRenderer wingsleft;
	    ModelRenderer Crest;
	    ModelRenderer clawLeft_Spikes;
	    ModelRenderer clawRight_Spikes;
	  
	  public ModelMegaScizor()
	  {
	    textureWidth = 80;
	    textureHeight = 80;
	    
	      hornright = new ModelRenderer(this, 13, 11);
	      hornright.addBox(-1.5F, -3.5F, -3F, 1, 4, 2);
	      hornright.setRotationPoint(0F, 0F, 0F);
	      hornright.setTextureSize(80, 80);
	      hornright.mirror = true;
	      setRotation(hornright, -0.3490659F, 0F, -0.4537856F);
	      hornright.mirror = false;
	      hornmiddle = new ModelRenderer(this, 13, 11);
	      hornmiddle.addBox(-0.5F, -3.5F, -3F, 1, 4, 2);
	      hornmiddle.setRotationPoint(0F, 0F, 0F);
	      hornmiddle.setTextureSize(80, 80);
	      hornmiddle.mirror = true;
	      setRotation(hornmiddle, -0.3490659F, 0F, 0F);
	      hornleft = new ModelRenderer(this, 13, 11);
	      hornleft.addBox(0.5F, -3.5F, -3F, 1, 4, 2);
	      hornleft.setRotationPoint(0F, 0F, 0F);
	      hornleft.setTextureSize(80, 80);
	      hornleft.mirror = true;
	      setRotation(hornleft, -0.3490659F, 0F, 0.4537856F);
	      headbottom = new ModelRenderer(this, 0, 11);
	      headbottom.addBox(-1.5F, -3F, 1F, 3, 1, 2);
	      headbottom.setRotationPoint(0F, 0F, 0F);
	      headbottom.setTextureSize(80, 80);
	      headbottom.mirror = true;
	      setRotation(headbottom, -2.86234F, 0F, 0F);
	      headtop = new ModelRenderer(this, 0, 0);
	      headtop.addBox(-2F, -1F, -3F, 4, 4, 4);
	      headtop.setRotationPoint(0F, 0F, 0F);
	      headtop.setTextureSize(80, 80);
	      headtop.mirror = true;
	      setRotation(headtop, 0.0174533F, 0F, 0F);
	      neck = new ModelRenderer(this, 22, 11);
	      neck.addBox(-1F, 1F, -1F, 2, 3, 2);
	      neck.setRotationPoint(0F, 0F, 0F);
	      neck.setTextureSize(80, 80);
	      neck.mirror = true;
	      setRotation(neck, 0F, 0F, 0F);
	      bodybottom = new ModelRenderer(this, 18, 28);
	      bodybottom.addBox(-1F, 7F, -1F, 2, 3, 2);
	      bodybottom.setRotationPoint(0F, 0F, 0F);
	      bodybottom.setTextureSize(80, 80);
	      bodybottom.mirror = true;
	      setRotation(bodybottom, 0F, 0F, 0F);
	      shoulderleft = new ModelRenderer(this, 40, 7);
	      shoulderleft.addBox(-1F, -0.5F, -1.6F, 4, 2, 3);
	      shoulderleft.setRotationPoint(2F, 4F, 0F);
	      shoulderleft.setTextureSize(80, 80);
	      shoulderleft.mirror = true;
	      setRotation(shoulderleft, 0F, 0F, 0F);
	      armleft = new ModelRenderer(this, 56, 0);
	      armleft.addBox(0F, 0.5F, -1F, 2, 6, 2);
	      armleft.setRotationPoint(2F, 4F, 0F);
	      armleft.setTextureSize(80, 80);
	      armleft.mirror = true;
	      setRotation(armleft, -0.6806784F, -0.5934119F, 0F);
	      clawleft = new ModelRenderer(this, 59, 15);
	      clawleft.addBox(-1F, 4.5F, 2F, 4, 8, 5);
	      clawleft.setRotationPoint(2F, 4F, 0F);
	      clawleft.setTextureSize(80, 80);
	      clawleft.mirror = true;
	      setRotation(clawleft, -1.27409F, -0.5934119F, 0F);
	      clawright = new ModelRenderer(this, 59, 15);
	      clawright.addBox(-3F, 4.5F, 2F, 4, 8, 5);
	      clawright.setRotationPoint(-2F, 4F, 0F);
	      clawright.setTextureSize(80, 80);
	      clawright.mirror = true;
	      setRotation(clawright, -1.27409F, 0.5934119F, 0F);
	      armright = new ModelRenderer(this, 56, 0);
	      armright.addBox(-2F, 0.5F, -1F, 2, 6, 2);
	      armright.setRotationPoint(-2F, 4F, 0F);
	      armright.setTextureSize(80, 80);
	      armright.mirror = true;
	      setRotation(armright, -0.6806784F, 0.5934119F, 0F);
	      shoulderright = new ModelRenderer(this, 40, 7);
	      shoulderright.addBox(-3F, -0.5F, -1.6F, 4, 2, 3);
	      shoulderright.setRotationPoint(-2F, 4F, 0F);
	      shoulderright.setTextureSize(80, 80);
	      shoulderright.mirror = true;
	      setRotation(shoulderright, 0F, 0F, 0F);
	      wingsright = new ModelRenderer(this, 41, 14);
	      wingsright.addBox(0F, -3F, 0.5F, 0, 7, 8);
	      wingsright.setRotationPoint(0F, 4F, 1F);
	      wingsright.setTextureSize(80, 80);
	      wingsright.mirror = true;
	      setRotation(wingsright, 0F, -0.5410521F, 0F);
	      thoraxbottom = new ModelRenderer(this, 0, 36);
	      thoraxbottom.addBox(-1.5F, 13F, -0.5F, 3, 2, 3);
	      thoraxbottom.setRotationPoint(0F, 0F, 0F);
	      thoraxbottom.setTextureSize(80, 80);
	      thoraxbottom.mirror = true;
	      setRotation(thoraxbottom, -0.1570796F, 0F, 0F);
	      leglefttoe = new ModelRenderer(this, 2, 75);
	      leglefttoe.addBox(0F, 12.5F, -2.5F, 1, 2, 2);
	      leglefttoe.setRotationPoint(2F, 11F, 0F);
	      leglefttoe.setTextureSize(80, 80);
	      leglefttoe.mirror = true;
	      setRotation(leglefttoe, 0F, 0F, -0.2792527F);
	      thoraxtop = new ModelRenderer(this, 0, 25);
	      thoraxtop.addBox(-2F, 9F, -1F, 4, 5, 4);
	      thoraxtop.setRotationPoint(0F, 0F, 0F);
	      thoraxtop.setTextureSize(80, 80);
	      thoraxtop.mirror = true;
	      setRotation(thoraxtop, -0.1570796F, 0F, 0F);
	      legrighttop = new ModelRenderer(this, 15, 47);
	      legrighttop.addBox(-2.5F, -1F, -2F, 4, 3, 2);
	      legrighttop.setRotationPoint(-2F, 11F, 0F);
	      legrighttop.setTextureSize(80, 80);
	      legrighttop.mirror = true;
	      setRotation(legrighttop, 0F, 0F, 0F);
	      legrightmiddle = new ModelRenderer(this, 0, 54);
	      legrightmiddle.addBox(-1F, 1F, -2.5F, 2, 5, 2);
	      legrightmiddle.setRotationPoint(-2F, 11F, 0F);
	      legrightmiddle.setTextureSize(80, 80);
	      legrightmiddle.mirror = true;
	      setRotation(legrightmiddle, 0F, 0F, 0.2792527F);
	      legrightbottom = new ModelRenderer(this, 0, 62);
	      legrightbottom.addBox(-1.5F, 4F, -3F, 3, 9, 3);
	      legrightbottom.setRotationPoint(-2F, 11F, 0F);
	      legrightbottom.setTextureSize(80, 80);
	      legrightbottom.mirror = true;
	      setRotation(legrightbottom, 0F, 0F, 0.2792527F);
	      legrighttoe = new ModelRenderer(this, 2, 75);
	      legrighttoe.addBox(-0.5F, 12.5F, -2.5F, 1, 2, 2);
	      legrighttoe.setRotationPoint(-2F, 11F, 0F);
	      legrighttoe.setTextureSize(80, 80);
	      legrighttoe.mirror = true;
	      setRotation(legrighttoe, 0F, 0F, 0.2792527F);
	      legleftbottom = new ModelRenderer(this, 0, 62);
	      legleftbottom.addBox(-1F, 4F, -3F, 3, 9, 3);
	      legleftbottom.setRotationPoint(2F, 11F, 0F);
	      legleftbottom.setTextureSize(80, 80);
	      legleftbottom.mirror = true;
	      setRotation(legleftbottom, 0F, 0F, -0.2792527F);
	      legleftmiddle = new ModelRenderer(this, 0, 54);
	      legleftmiddle.addBox(-0.5F, 1F, -2.5F, 2, 5, 2);
	      legleftmiddle.setRotationPoint(2F, 11F, 0F);
	      legleftmiddle.setTextureSize(80, 80);
	      legleftmiddle.mirror = true;
	      setRotation(legleftmiddle, 0F, 0F, -0.2792527F);
	      leglefttop = new ModelRenderer(this, 15, 47);
	      leglefttop.addBox(-1.5F, -1F, -2F, 4, 3, 2);
	      leglefttop.setRotationPoint(2F, 11F, 0F);
	      leglefttop.setTextureSize(80, 80);
	      leglefttop.mirror = true;
	      setRotation(leglefttop, 0F, 0F, 0F);
	      bodytop = new ModelRenderer(this, 23, 0);
	      bodytop.addBox(-2F, 4F, -1.5F, 4, 4, 3);
	      bodytop.setRotationPoint(0F, 0F, 0F);
	      bodytop.setTextureSize(80, 80);
	      bodytop.mirror = true;
	      setRotation(bodytop, 0F, 0F, 0F);
	      wingsleft = new ModelRenderer(this, 41, 14);
	      wingsleft.addBox(0F, -3F, 0.5F, 0, 7, 8);
	      wingsleft.setRotationPoint(0F, 4F, 1F);
	      wingsleft.setTextureSize(80, 80);
	      wingsleft.mirror = true;
	      setRotation(wingsleft, 0F, 0.5410521F, 0F);
	      Crest = new ModelRenderer(this, 19, 40);
	      Crest.addBox(-2F, -1F, -3.5F, 4, 4, 1);
	      Crest.setRotationPoint(0F, -0.5F, 0F);
	      Crest.setTextureSize(80, 80);
	      Crest.mirror = true;
	      setRotation(Crest, 0.0174533F, 0F, 0F);
	      clawLeft_Spikes = new ModelRenderer(this, 60, 35);
	      clawLeft_Spikes.addBox(1F, 4.5F, 7F, 1, 8, 2);
	      clawLeft_Spikes.setRotationPoint(2F, 4F, 0F);
	      clawLeft_Spikes.setTextureSize(80, 80);
	      clawLeft_Spikes.mirror = true;
	      setRotation(clawLeft_Spikes, -1.27409F, -0.5934119F, 0F);
	      clawRight_Spikes = new ModelRenderer(this, 60, 35);
	      clawRight_Spikes.addBox(-1F, 4.5F, 7F, 1, 8, 2);
	      clawRight_Spikes.setRotationPoint(-2F, 4F, 0F);
	      clawRight_Spikes.setTextureSize(80, 80);
	      clawRight_Spikes.mirror = true;
	      setRotation(clawRight_Spikes, -1.27409F, 0.5934119F, 0F);
	  }
	  
	  @Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.render(entity, f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	    hornright.render(f5);
	    hornmiddle.render(f5);
	    hornleft.render(f5);
	    headbottom.render(f5);
	    headtop.render(f5);
	    neck.render(f5);
	    bodybottom.render(f5);
	    shoulderleft.render(f5);
	    armleft.render(f5);
	    clawleft.render(f5);
	    clawright.render(f5);
	    armright.render(f5);
	    shoulderright.render(f5);
	    wingsright.render(f5);
	    thoraxbottom.render(f5);
	    leglefttoe.render(f5);
	    thoraxtop.render(f5);
	    legrighttop.render(f5);
	    legrightmiddle.render(f5);
	    legrightbottom.render(f5);
	    legrighttoe.render(f5);
	    legleftbottom.render(f5);
	    legleftmiddle.render(f5);
	    leglefttop.render(f5);
	    bodytop.render(f5);
	    wingsleft.render(f5);
	    Crest.render(f5);
	    clawLeft_Spikes.render(f5);
	    clawRight_Spikes.render(f5);
	  }
	  @Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
	  {
	    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	  }

	}
