package pokecube.adventures.client.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import pokecube.core.client.models.APokemobModel;

public class ModelMegaSalamence extends APokemobModel {
  //fields
    ModelRenderer Body;
    ModelRenderer Left_hindleg_shin;
    ModelRenderer Left_hindleg_lower;
    ModelRenderer Left_hindclaws;
    ModelRenderer Right_hindleg_shin;
    ModelRenderer Right_hindleg_lower;
    ModelRenderer Right_hindclaws;
    ModelRenderer Bodyplates;
    ModelRenderer Neck_pt1;
    ModelRenderer Neck_pt2;
    ModelRenderer Head_base;
    ModelRenderer Head_snoutpt1;
    ModelRenderer Head_snout_tip;
    ModelRenderer Head_ridge_2;
    ModelRenderer Head_ridge_4;
    ModelRenderer Jaw_base;
    ModelRenderer Jaw_pt2;
    ModelRenderer Jaw_tip;
    ModelRenderer Left_mid_fin;
    ModelRenderer Left_top_fin;
    ModelRenderer Left_btm_fin;
    ModelRenderer Right_top_fin;
    ModelRenderer Right_mid_fin;
    ModelRenderer Right_btm_fin;
    ModelRenderer Tail_base;
    ModelRenderer Tail_pt2;
    ModelRenderer Tail_tip;
    ModelRenderer Tail_tip_end;
    ModelRenderer Right_overshield;
    ModelRenderer Right_overshieldtip;
    ModelRenderer Left_overshield;
    ModelRenderer Left_overshieldtip;
    ModelRenderer Left_wing;
    ModelRenderer Right_wing;
    ModelRenderer Left_arm;
    ModelRenderer Right_arm;
  
  public ModelMegaSalamence()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-7.5F, -6F, -12F, 15, 10, 23);
      Body.setRotationPoint(0F, 13F, 0F);
      Body.setTextureSize(256, 256);
      Body.mirror = true;
      setRotation(Body, -0.1396263F, 0F, 0F);
      Left_hindleg_shin = new ModelRenderer(this, 0, 34);
      Left_hindleg_shin.addBox(0F, -1F, -3F, 6, 9, 6);
      Left_hindleg_shin.setRotationPoint(5F, 14F, 8F);
      Left_hindleg_shin.setTextureSize(256, 256);
      Left_hindleg_shin.mirror = true;
      setRotation(Left_hindleg_shin, 1.570796F, 0.5235988F, 0F);
      Left_hindleg_lower = new ModelRenderer(this, 25, 34);
      Left_hindleg_lower.addBox(1F, 6F, -3F, 6, 8, 6);
      Left_hindleg_lower.setRotationPoint(5F, 14F, 8F);
      Left_hindleg_lower.setTextureSize(256, 256);
      Left_hindleg_lower.mirror = true;
      setRotation(Left_hindleg_lower, 1.570796F, 0.3665191F, 0F);
      Left_hindclaws = new ModelRenderer(this, 49, 34);
      Left_hindclaws.addBox(1.5F, 13F, -4F, 5, 1, 1);
      Left_hindclaws.setRotationPoint(5F, 14F, 8F);
      Left_hindclaws.setTextureSize(256, 256);
      Left_hindclaws.mirror = true;
      setRotation(Left_hindclaws, 1.570796F, 0.3665191F, 0F);
      Right_hindleg_shin = new ModelRenderer(this, 0, 34);
      Right_hindleg_shin.addBox(-6F, -1F, -3F, 6, 9, 6);
      Right_hindleg_shin.setRotationPoint(-5F, 14F, 8F);
      Right_hindleg_shin.setTextureSize(256, 256);
      Right_hindleg_shin.mirror = true;
      setRotation(Right_hindleg_shin, 1.570796F, -0.5235988F, 0F);
      Right_hindleg_lower = new ModelRenderer(this, 25, 34);
      Right_hindleg_lower.addBox(-7F, 6F, -3F, 6, 8, 6);
      Right_hindleg_lower.setRotationPoint(-5F, 14F, 8F);
      Right_hindleg_lower.setTextureSize(256, 256);
      Right_hindleg_lower.mirror = true;
      setRotation(Right_hindleg_lower, 1.570796F, -0.3665191F, 0F);
      Right_hindclaws = new ModelRenderer(this, 49, 34);
      Right_hindclaws.addBox(-6.5F, 13F, -4F, 5, 1, 1);
      Right_hindclaws.setRotationPoint(-5F, 14F, 8F);
      Right_hindclaws.setTextureSize(256, 256);
      Right_hindclaws.mirror = true;
      setRotation(Right_hindclaws, 1.570796F, -0.3665191F, 0F);
      Bodyplates = new ModelRenderer(this, 70, 0);
      Bodyplates.addBox(-5.5F, 4F, -4F, 11, 1, 12);
      Bodyplates.setRotationPoint(0F, 13F, 0F);
      Bodyplates.setTextureSize(256, 256);
      Bodyplates.mirror = true;
      setRotation(Bodyplates, -0.1396263F, 0F, 0F);
      Neck_pt1 = new ModelRenderer(this, 0, 49);
      Neck_pt1.addBox(-3.5F, -3.5F, -12F, 7, 7, 12);
      Neck_pt1.setRotationPoint(0F, 9F, -10F);
      Neck_pt1.setTextureSize(256, 256);
      Neck_pt1.mirror = true;
      setRotation(Neck_pt1, 0F, 0F, 0F);
      Neck_pt2 = new ModelRenderer(this, 0, 68);
      Neck_pt2.addBox(-3.5F, -3.5F, -8F, 7, 7, 8);
      Neck_pt2.setRotationPoint(0F, 9F, -22F);
      Neck_pt2.setTextureSize(256, 256);
      Neck_pt2.mirror = true;
      setRotation(Neck_pt2, 0F, 0F, 0F);
      Head_base = new ModelRenderer(this, 30, 68);
      Head_base.addBox(-4.5F, -6F, -8F, 9, 6, 8);
      Head_base.setRotationPoint(0F, 11F, -30F);
      Head_base.setTextureSize(256, 256);
      Head_base.mirror = true;
      setRotation(Head_base, 0F, 0F, 0F);
      Head_snoutpt1 = new ModelRenderer(this, 30, 83);
      Head_snoutpt1.addBox(-4F, -5.5F, -11F, 8, 5, 3);
      Head_snoutpt1.setRotationPoint(0F, 11F, -30F);
      Head_snoutpt1.setTextureSize(256, 256);
      Head_snoutpt1.mirror = true;
      setRotation(Head_snoutpt1, 0F, 0F, 0F);
      Head_snout_tip = new ModelRenderer(this, 10, 83);
      Head_snout_tip.addBox(-3F, -4.5F, -14F, 6, 4, 3);
      Head_snout_tip.setRotationPoint(0F, 11F, -30F);
      Head_snout_tip.setTextureSize(256, 256);
      Head_snout_tip.mirror = true;
      setRotation(Head_snout_tip, 0F, 0F, 0F);
      Head_ridge_2 = new ModelRenderer(this, 55, 49);
      Head_ridge_2.addBox(-4F, -7F, -7.5F, 2, 1, 6);
      Head_ridge_2.setRotationPoint(0F, 11F, -30F);
      Head_ridge_2.setTextureSize(256, 256);
      Head_ridge_2.mirror = true;
      setRotation(Head_ridge_2, 0.0872665F, 0F, 0F);
      Head_ridge_4 = new ModelRenderer(this, 55, 49);
      Head_ridge_4.addBox(2F, -7F, -7.5F, 2, 1, 6);
      Head_ridge_4.setRotationPoint(0F, 11F, -30F);
      Head_ridge_4.setTextureSize(256, 256);
      Head_ridge_4.mirror = true;
      setRotation(Head_ridge_4, 0.0872665F, 0F, 0F);
      Jaw_base = new ModelRenderer(this, 64, 68);
      Jaw_base.addBox(-4F, -1F, -8F, 8, 2, 7);
      Jaw_base.setRotationPoint(0F, 11F, -30F);
      Jaw_base.setTextureSize(256, 256);
      Jaw_base.mirror = true;
      setRotation(Jaw_base, 0F, 0F, 0F);
      Jaw_pt2 = new ModelRenderer(this, 64, 63);
      Jaw_pt2.addBox(-3.5F, -1.5F, -10F, 7, 2, 2);
      Jaw_pt2.setRotationPoint(0F, 11F, -30F);
      Jaw_pt2.setTextureSize(256, 256);
      Jaw_pt2.mirror = true;
      setRotation(Jaw_pt2, 0F, 0F, 0F);
      Jaw_tip = new ModelRenderer(this, 64, 57);
      Jaw_tip.addBox(-2.5F, 0.5F, -13F, 5, 1, 4);
      Jaw_tip.setRotationPoint(0F, 11F, -30F);
      Jaw_tip.setTextureSize(256, 256);
      Jaw_tip.mirror = true;
      setRotation(Jaw_tip, -0.1570796F, 0F, 0F);
      Left_mid_fin = new ModelRenderer(this, 65, 103);
      Left_mid_fin.addBox(4.5F, -2F, -7F, 9, 1, 7);
      Left_mid_fin.setRotationPoint(0F, 11F, -30F);
      Left_mid_fin.setTextureSize(256, 256);
      Left_mid_fin.mirror = true;
      setRotation(Left_mid_fin, 0F, 0F, 0F);
      Left_top_fin = new ModelRenderer(this, 65, 86);
      Left_top_fin.addBox(7F, 1F, -4F, 9, 1, 4);
      Left_top_fin.setRotationPoint(0F, 11F, -30F);
      Left_top_fin.setTextureSize(256, 256);
      Left_top_fin.mirror = true;
      setRotation(Left_top_fin, 0F, 0F, -1.134464F);
      Left_btm_fin = new ModelRenderer(this, 65, 86);
      Left_btm_fin.addBox(0.7F, -3.5F, -4F, 9, 1, 4);
      Left_btm_fin.setRotationPoint(0F, 11F, -30F);
      Left_btm_fin.setTextureSize(256, 256);
      Left_btm_fin.mirror = true;
      setRotation(Left_btm_fin, 0F, 0F, 0.7853982F);
      Right_top_fin = new ModelRenderer(this, 65, 80);
      Right_top_fin.addBox(-15.3F, 1F, -4F, 9, 1, 4);
      Right_top_fin.setRotationPoint(0F, 11F, -30F);
      Right_top_fin.setTextureSize(256, 256);
      Right_top_fin.mirror = true;
      setRotation(Right_top_fin, 0F, 0F, 1.134464F);
      Right_mid_fin = new ModelRenderer(this, 65, 114);
      Right_mid_fin.addBox(-13.5F, -2F, -7F, 9, 1, 7);
      Right_mid_fin.setRotationPoint(0F, 11F, -30F);
      Right_mid_fin.setTextureSize(256, 256);
      Right_mid_fin.mirror = true;
      setRotation(Right_mid_fin, 0F, 0F, 0F);
      Right_btm_fin = new ModelRenderer(this, 65, 80);
      Right_btm_fin.addBox(-9.3F, -3.5F, -4F, 9, 1, 4);
      Right_btm_fin.setRotationPoint(0F, 11F, -30F);
      Right_btm_fin.setTextureSize(256, 256);
      Right_btm_fin.mirror = true;
      setRotation(Right_btm_fin, 0F, 0F, -0.7853982F);
      Tail_base = new ModelRenderer(this, 78, 20);
      Tail_base.addBox(-3F, -3F, 0F, 6, 6, 17);
      Tail_base.setRotationPoint(0F, 14F, 11F);
      Tail_base.setTextureSize(256, 256);
      Tail_base.mirror = true;
      setRotation(Tail_base, 0F, 0F, 0F);
      Tail_pt2 = new ModelRenderer(this, 78, 43);
      Tail_pt2.addBox(-2.5F, -2.5F, 0F, 5, 5, 10);
      Tail_pt2.setRotationPoint(0F, 14F, 28F);
      Tail_pt2.setTextureSize(256, 256);
      Tail_pt2.mirror = true;
      setRotation(Tail_pt2, 0F, 0F, 0F);
      Tail_tip = new ModelRenderer(this, 94, 58);
      Tail_tip.addBox(-1.5F, -1.5F, 0F, 3, 3, 10);
      Tail_tip.setRotationPoint(0F, 14F, 38F);
      Tail_tip.setTextureSize(256, 256);
      Tail_tip.mirror = true;
      setRotation(Tail_tip, 0F, 0F, 0F);
      Tail_tip_end = new ModelRenderer(this, 94, 76);
      Tail_tip_end.addBox(-1F, -1F, 0F, 2, 2, 8);
      Tail_tip_end.setRotationPoint(0F, 14F, 48F);
      Tail_tip_end.setTextureSize(256, 256);
      Tail_tip_end.mirror = true;
      setRotation(Tail_tip_end, 0F, 0F, 0F);
      Right_overshield = new ModelRenderer(this, 0, 92);
      Right_overshield.addBox(-10.5F, -6.5F, -13F, 5, 11, 23);
      Right_overshield.setRotationPoint(0F, 13F, 0F);
      Right_overshield.setTextureSize(256, 256);
      Right_overshield.mirror = true;
      setRotation(Right_overshield, -0.1396263F, 0F, 0F);
      Right_overshieldtip = new ModelRenderer(this, 40, 92);
      Right_overshieldtip.addBox(-10.5F, -4.5F, -17F, 5, 7, 4);
      Right_overshieldtip.setRotationPoint(0F, 13F, 0F);
      Right_overshieldtip.setTextureSize(256, 256);
      Right_overshieldtip.mirror = true;
      setRotation(Right_overshieldtip, -0.1396263F, 0F, 0F);
      Left_overshield = new ModelRenderer(this, 0, 92);
      Left_overshield.addBox(5.5F, -6.5F, -13F, 5, 11, 23);
      Left_overshield.setRotationPoint(0F, 13F, 0F);
      Left_overshield.setTextureSize(256, 256);
      Left_overshield.mirror = true;
      setRotation(Left_overshield, -0.1396263F, 0F, 0F);
      Left_overshieldtip = new ModelRenderer(this, 40, 92);
      Left_overshieldtip.addBox(5.5F, -4.5F, -17F, 5, 7, 4);
      Left_overshieldtip.setRotationPoint(0F, 13F, 0F);
      Left_overshieldtip.setTextureSize(256, 256);
      Left_overshieldtip.mirror = true;
      setRotation(Left_overshieldtip, -0.1396263F, 0F, 0F);
      Left_wing = new ModelRenderer(this, 0, 126);
      Left_wing.addBox(7F, -5F, -33F, 65, 1, 60);
      Left_wing.setRotationPoint(0F, 13F, 0F);
      Left_wing.setTextureSize(256, 256);
      Left_wing.mirror = true;
      setRotation(Left_wing, -0.1396263F, -0.2268928F, -0.1919862F);
      Right_wing = new ModelRenderer(this, 0, 192);
      Right_wing.addBox(-72F, -5F, -33F, 65, 1, 60);
      Right_wing.setRotationPoint(0F, 13F, 0F);
      Right_wing.setTextureSize(256, 256);
      Right_wing.mirror = true;
      setRotation(Right_wing, -0.1396263F, 0.2268928F, 0.1919862F);
      Left_arm = new ModelRenderer(this, 0, 0);
      Left_arm.addBox(0F, -4F, -3F, 4, 9, 6);
      Left_arm.setRotationPoint(7F, 11F, -10F);
      Left_arm.setTextureSize(256, 256);
      Left_arm.mirror = true;
      setRotation(Left_arm, 1.413717F, 0F, 0F);
      Right_arm = new ModelRenderer(this, 0, 0);
      Right_arm.addBox(-4F, -4F, -3F, 4, 9, 6);
      Right_arm.setRotationPoint(-7F, 11F, -10F);
      Right_arm.setTextureSize(256, 256);
      Right_arm.mirror = true;
      setRotation(Right_arm, 1.413717F, 0F, 0F);
  }
  
  @Override
public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    Left_hindleg_shin.render(f5);
    Left_hindleg_lower.render(f5);
    Left_hindclaws.render(f5);
    Right_hindleg_shin.render(f5);
    Right_hindleg_lower.render(f5);
    Right_hindclaws.render(f5);
    Bodyplates.render(f5);
    Neck_pt1.render(f5);
    Neck_pt2.render(f5);
    Head_base.render(f5);
    Head_snoutpt1.render(f5);
    Head_snout_tip.render(f5);
    Head_ridge_2.render(f5);
    Head_ridge_4.render(f5);
    Jaw_base.render(f5);
    Jaw_pt2.render(f5);
    Jaw_tip.render(f5);
    Left_mid_fin.render(f5);
    Left_top_fin.render(f5);
    Left_btm_fin.render(f5);
    Right_top_fin.render(f5);
    Right_mid_fin.render(f5);
    Right_btm_fin.render(f5);
    Tail_base.render(f5);
    Tail_pt2.render(f5);
    Tail_tip.render(f5);
    Tail_tip_end.render(f5);
    Right_overshield.render(f5);
    Right_overshieldtip.render(f5);
    Left_overshield.render(f5);
    Left_overshieldtip.render(f5);
    Left_wing.render(f5);
    Right_wing.render(f5);
    Left_arm.render(f5);
    Right_arm.render(f5);
  }
  
  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}